language: python

jobs:
  fast_finish: true
  # Travis exclude is buggy, this seems to be the only way to disable default build
  exclude:
    - language: ruby
  include:
    # default builds for Linux
    - os: linux
      arch: amd64
      dist: xenial
      python: 3.6
    - os: linux
      arch: amd64
      dist: xenial
      python: 3.7
    - os: linux
      arch: amd64
      dist: xenial
      python: 3.8
    - os: linux
      arch: amd64
      dist: xenial
      python: 3.9 

# The first line is printed in the folding header in Travis output
before_install: 
  - pip install cython scikit-learn scikit-build

install: 
  - python setup.py install

script: 
  - cd tests
  - pytest get_build_info.py
  - pytest test.py
