git:
    submodules: false

# https://docs.travis-ci.com/user/caching
cache:
  directories:
    # `cache: ccache: true` has no effect if `language:` is not `c` or `cpp`
    - $HOME/.ccache

# Add more cache stages (s2 etc) and corresponding OSX jobs like s1
# if brew builds start to take longer than one Travis time limit
stages:
  - final

jobs:
  fast_finish: true
  # Travis exclude is buggy, this seems to be the only way to disable default build
  exclude:
    - language: ruby
  include:
    # default builds for Linux
    - os: linux
      arch: amd64
      language: generic
      dist: xenial
      python: 3.6
    - os: linux
      arch: amd64
      language: generic
      dist: xenial
      python: 3.7
    - os: linux
      arch: amd64
      language: generic
      dist: xenial
      python: 3.8
    - os: linux
      arch: amd64
      language: generic
      dist: xenial
      python: 3.9 

# The first line is printed in the folding header in Travis output
before_install: 
  - pip install cython scikit-learn

install: 
  - python setup.py install

script: 
  - cd tests
  - pytest get_build_info.py
  - pytest test.py
